name: Build and Test App

env:
  DOTNET_VERSION: '6.0'                 # set this to the .NET version to use

on:
  push:
    branches-ignore:    
      - 'main'
      - 'develop'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{env.DOTNET_VERSION}} # Adjust the version as needed

      - name: Check for Formatting errors
        run: dotnet format src --verify-no-changes    

      - name: Build
        run: dotnet build src

      - name: Test
        run: dotnet test src --no-restore --verbosity normal
