name: Build and Test Workflow

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  build-test-format:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0' # Adjust the version as needed

    - name: Build
      run: dotnet build src --configuration Release

    - name: Test
      run: dotnet test src --configuration Release --no-restore --verbosity normal

    - name: Format
      run: dotnet format src --check --verbosity normal
    
    - name: Build docker image
        run:|
          docker build src -t test/test:latest 
